# Generated by Django 2.0 on 2018-06-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpyDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'db_table': 'dpy_department',
            },
        ),
        migrations.CreateModel(
            name='DpyInstituteClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=100)),
                ('batch', models.PositiveSmallIntegerField(default=1)),
                ('sort_index', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyDepartment')),
            ],
            options={
                'verbose_name': 'Institute Class',
                'db_table': 'dpy_institute_class',
            },
        ),
        migrations.CreateModel(
            name='DpyInstituteClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('ic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteClass')),
            ],
            options={
                'verbose_name': 'Institute Class Session',
                'db_table': 'dpy_class_session',
            },
        ),
        migrations.CreateModel(
            name='DpyInstituteClassSessionSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default=0)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteClassSession')),
            ],
            options={
                'verbose_name': 'Class Session Subject',
                'db_table': 'dpy_class_session_subject',
            },
        ),
    ]
