# Generated by Django 2.0.5 on 2018-07-10 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_user_profiling', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpyinstituteuserclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteuseradditionalfield',
            name='iaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteAdditionalField'),
        ),
        migrations.AddField(
            model_name='dpyinstituteuseradditionalfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='css',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteClassSessionSubject'),
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubjectuser',
            name='css',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='class_user_profiling.DpyInstituteClassSessionSubject'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubjectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubject',
            name='cs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='class_user_profiling.DpyInstituteClassSession'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssession',
            name='ic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_session', to='class_user_profiling.DpyInstituteClass'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='class_user_profiling.DpyDepartment'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclass',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.AddField(
            model_name='dpyinstituteadditionalfield',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.AddField(
            model_name='dpydepartment',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
    ]
