# Generated by Django 2.0.5 on 2018-07-10 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_user_profiling', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpyinstituteuserclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteuseradditionalfield',
            name='iaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteAdditionalField'),
        ),
        migrations.AddField(
            model_name='dpyinstituteuseradditionalfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='css',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='class_user_profiling.DpyInstituteClassSessionSubject'),
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.AddField(
            model_name='dpyinstitutetimetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubjectuser',
            name='css',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='class_user_profiling.DpyInstituteClassSessionSubject'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubjectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssessionsubject',
            name='cs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject', to='class_user_profiling.DpyInstituteClassSession'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclasssession',
            name='ic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_session', to='class_user_profiling.DpyInstituteClass'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='class_user_profiling.DpyDepartment'),
        ),
        migrations.AddField(
            model_name='dpyinstituteclass',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.AddField(
            model_name='dpyinstituteadditionalfield',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.AddField(
            model_name='dpydepartment',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.DpyInstitute'),
        ),
        migrations.RunSQL("ALTER TABLE dpy_department CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `id`"),
        migrations.RunSQL("ALTER TABLE dpy_department CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_department CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_additional_field CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `field_type`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_additional_field CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_additional_field CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_additional_field CHANGE `field_type` `field_type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0:varchar,1:date,2:Int' AFTER `name`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_class CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `sort_index`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_class CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_class CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_class CHANGE `batch` `batch` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `division`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_class CHANGE `sort_index` `sort_index` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `batch`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `prerequisite_session`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `prerequisite_subject`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject_user CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `user_type`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject_user CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject_user CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_class_session_subject_user CHANGE `user_type` `user_type`  tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '1:Student,2:Teacher' AFTER `user_id`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_time_table CHANGE `day_id` `day_id` tinyint(1) unsigned NOT NULL AFTER `lecture_no`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_time_table CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `day_id`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_time_table CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_time_table CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_additional_field CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `value`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_additional_field CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_additional_field CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_class CHANGE `is_class_teacher` `is_class_teacher` tinyint(1) unsigned NOT NULL DEFAULT '0' AFTER `roll_no`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_class CHANGE `status` `status` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `is_class_teacher`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_class CHANGE `created_on` `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `status`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_class CHANGE `updated_on` `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_by`"),
        migrations.RunSQL("ALTER TABLE dpy_institute_user_class CHANGE `user_type` `user_type`  tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '1:Student,2:Teacher' AFTER `id`"),        
    ]
