# Generated by Django 2.0.5 on 2018-07-13 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_user_profiling', '0002_auto_20180710_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dpyinstituteclasssessionsubjectuser',
            unique_together={('css', 'user', 'user_type')},
        ),
    ]
