# Generated by Django 2.0.5 on 2018-07-17 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_user_profiling', '0004_auto_20180713_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpyinstituteclassuserpresenties',
            name='date',
            field=models.DateField(default="2018-07-17"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dpyinstituteclassuserpresenties',
            name='css',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_info', to='class_user_profiling.DpyInstituteClassSessionSubject'),
        ),
        migrations.AlterField(
            model_name='dpyinstituteclassuserpresenties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
