# Generated by Django 2.0 on 2018-07-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpyinstituteadmissionsusers',
            options={'managed': True},
        ),
    ]
