# Generated by Django 2.0 on 2018-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpyLeaveTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.IntegerField(db_column='Leave_name')),
                ('leaves_remaining', models.IntegerField(db_column='Leaves_remaining')),
                ('created_on', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.IntegerField()),
            ],
            options={
                'db_table': 'dpy_leave_types',
                'managed': False,
            },
        ),
    ]
